language: bash
dist: bionic

addons:
  snaps:
    - snapcraft

stages:
  - lint
  - build
  - deploy

jobs:
  include:
    - stage: lint
      script: echo lint
    - stage: build
      script: snapcraft
    - stage: deploy
      script: skip
      deploy:
        - provider: snap
          skip_cleanup: true
          snap: "*.snap"
          channel: stable
          on:
            tags: true
        - provider: snap
          skip_cleanup: true
          snap: "*.snap"
          channel: edge
          on:
            branch: master
        - provider: snap
          skip_cleanup: true
          snap: "*.snap"
          channel: edge/$TRAVIS_BRANCH
          on:
            all_branches: true
            condition: $TRAVIS_BRANCH != master
