language: generic

services:
  - docker

stages:
  - lint
  - build
  - deploy

jobs:
  include:
    - stage: lint
      script: echo lint
    - stage: build
      script: echo build

deploy:
  - provider: snap
    snap: "*.snap"
    skip_cleanup: true
    channel: stable
    on:
      tags: true

  - provider: snap
    snap: "*.snap"
    skip_cleanup: true
    channel: edge
    on:
      branch: master

  - provider: snap
    snap: "*.snap"
    skip_cleanup: true
    channel: edge/$TRAVIS_BRANCH
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH != master
