language: bash
dist: bionic

addons:
  snaps:
    - name: snapcraft
      confinement: classic

stages:
  - deploy

jobs:
  include:
    - stage: deploy
      script: snapcraft
      deploy:
        - provider: snap
          skip_cleanup: true
          snap: "*.snap"
          channel: stable
          on:
            tags: true
        - provider: snap
          skip_cleanup: true
          snap: "*.snap"
          channel: edge
          on:
            tags: false
        - provider: snap
          skip_cleanup: true
          snap: "*.snap"
          channel: edge/$TRAVIS_BRANCH
          on:
            tags: false
            all_branches: true
            condition: $TRAVIS_BRANCH != master
